[supervisord]
nodaemon=true

[program:server]
command=node server.js
directory=/usr/src/app
autostart=true
autorestart=true

[program:frontend]
command=npm run start --prefix reoxplore
directory=/usr/src/app
autostart=true
autorestart=true